version: "3.4"
services:

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ../somatik-laravel/.docker/mysql/data:/var/lib/mysql
    # Uses port 3306
    ports:
      - 3306:3306

  php-fpm:
    image: zeckson/php-fpm:0.5
    environment:
      - PHP_IDE_CONFIG=serverName=somatik-php
    build:
      context: ./.docker/php-fpm
    depends_on:
      - mysql
    volumes:
      - .:/application
      - ./.docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/php.ini
      - ./.docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf

  webserver:
    image: nginx:alpine
    restart: always
    depends_on:
      - php-fpm
    volumes:
      - .:/application
      - ./static/build:/static
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

# Disabled services
x-services:
  composer:
    image: composer
    volumes:
      - .:/app
    command: install

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    depends_on:
      - mysql
