version: "3.1"
services:

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    # Uses port 3306
    networks:
      - code-network

  webserver:
    image: nginx:alpine
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  composer:
    image: composer
    volumes:
      - .:/app
    command: install

  php-fpm:
    image: zeckson/php-fpm:0.4
    build:
      context: ./.docker/php-fpm
    volumes:
      - .:/application
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

networks:
  code-network:
    driver: bridge
